@echo off
chcp 65001 >nul
echo 正在启动 Lang Drill Agent 服务...

echo [1/2] 启动后端服务...
start "LangDrill Backend" cmd /k ".\.venv\Scripts\activate.bat && py -m langdrill_agent.cli serve --reload"

echo [2/2] 启动前端服务...
start "LangDrill Frontend" cmd /k "cd frontend && npm run dev"

echo 等待服务初始化 (约 4 秒)...
timeout /t 4 /nobreak >nul

echo 正在打开浏览器...
start http://127.0.0.1:5173
